let mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .js('resources/js/legacy/libs/jquery/jquery.3.7.0.js', 'public/js/legacy/libs')
    .js('resources/js/legacy/libs/nice_select/jquery.nice-select.min.js', 'public/js/legacy/libs')
    .js('resources/js/legacy/libs/jquery_ui_slider/jquery-ui.min.js', 'public/js/legacy/libs/jquery-ui.min.js')
    .js('resources/js/legacy/libs/slick/slick.min.js', 'public/js/legacy/libs')
    .js('resources/js/legacy/libs/custom_scroll/jquery.mCustomScrollbar.js', 'public/js/legacy/libs')
    .js('resources/js/legacy/libs/jquery_maskedinput/jquery.maskedinput.min.js', 'public/js/legacy/libs')
    .js('resources/js/legacy/blocks.js', 'public/js/legacy/')
    .js('resources/js/legacy/script.js', 'public/js/legacy/')
    .js('resources/js/legacy/plugins/select2/js/select2.full.min.js', 'public/js/legacy/libs/select2.min.js')
    .js('resources/js/legacy/plugins/jquery/jquery.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/jquery-ui/jquery-ui.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/bootstrap/js/bootstrap.bundle.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/chart.js/Chart.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/sparklines/sparkline.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/jqvmap/jquery.vmap.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/jqvmap/maps/jquery.vmap.usa.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/jquery-knob/jquery.knob.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/moment/moment.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/daterangepicker/daterangepicker.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/summernote/summernote-bs4.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/plugins/select2/js/select2.full.min.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/admin/adminlte.js', 'public/js/legacy/plugins')
    .js('resources/js/legacy/googletagmager.js', 'public/js/legacy')

    .js('resources/js/regularReces/sripts.js', 'public/js/regularReces/sripts.js')

    .postCss('resources/css/legacy/libs/nice_select/nice-select.css', 'public/css/legacy/libs/nice_select/nice-select.css')
    .postCss('resources/css/legacy/libs/jquery_ui_slider/jquery-ui.min.css', 'public/css/legacy/libs/jquery_ui_slider/jquery-ui.min.css')
    .postCss('resources/css/legacy/libs/slick/slick.css', 'public/css/legacy/libs/slick/slick.css')
    .postCss('resources/css/legacy/libs/custom_scroll/jquery.mCustomScrollbar.min.css', 'public/css/legacy/libs/slick/jquery.mCustomScrollbar.min.css')
    .postCss('resources/css/legacy/libs/bootstrap/bootstrap.min.css', 'public/css/legacy/bootstrap/bootstrap.min.css')
    .postCss('resources/css/legacy/style_table.css', 'public/css/legacy/style_table.css')
    .postCss('resources/css/legacy/responsive.css', 'public/css/responsive.css')
    .postCss('resources/css/legacy/nag.css', 'public/css/nag.css')
    .postCss('resources/css/legacy/common.css', 'public/css/common.css')
    .postCss('resources/css/legacy/style.css', 'public/css/style.css')
    .postCss('resources/css/legacy/mobile.css', 'public/css/mobile.css')
    .postCss('resources/css/header-new.css', 'public/css/header-new.css')

    .postCss('resources/admin/plugins/fontawesome-free/css/all.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/jqvmap/jqvmap.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/select2/css/select2.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/css/adminlte.css', 'public/css/admin')
    .postCss('resources/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/daterangepicker/daterangepicker.css', 'public/css/admin/plugins')
    .postCss('resources/admin/plugins/summernote/summernote-bs4.min.css', 'public/css/admin/plugins')
    .postCss('resources/css/legacy/admin/style.css', 'public/css/admin')

    .setPublicPath('public');
